language: java
jdk:
  - oraclejdk8
#before_install:
#- cd textclassifier2_core
#- chmod +x gradlew
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
