spring.profiles: test
# use local or embedded mongodb at localhost:27017
# spring.data.mongodb.uri: mongodb://localhost:27017/jiradb
---
spring.profiles: production
spring.data.mongodb.uri: mongodb+srv://admin:kentdfu!@cluster0-bsfqs.mongodb.net/test